version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5436:5432

  app:
    container_name: nest-graphql
    build:
      context: ./
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 3002:3000
    environment:
      - PORT=${PORT}
      - API_LOCAL_PORT=${API_LOCAL_PORT}
      - API_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
